#+title: Bank Portfolio Immunization
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

Assume a bank has the following (very simplified) balance sheet.

* Assets

Mortgages

-  Fixed rate, 15 year, annual payments, both the coupon rate and yield-to-maturity are 8% 

-  Floating rate, 15 year, rate: LIBOR + 2%,  (duration = 0)

* Liabilities

-  Overnight deposits, rate: 0.6%, (duration = 0)

-  2 year CD, rate: 2%, assume it is a zero coupon

-  3 year CD, rate: 4%, assume it is a zero coupon

* Assignment

1.  Calculate weights which will immunize the portfolio.  Note this is a set of weights, there is not one unique solution.  You don't have to calculate the full set, just some set of weights which immunizes the portfolio.

2.  Now say you can only invest 50% of your assets in floating rate mortgages.  What is the minimum amount of interest rate risk you can have?  What will happen to the value of your portfolio if interest rates increase by 1%?
